### ISSUE TITLE
[Repository] Add a `failed check` label to any PR that fails a GH check

### ISSUE THREAD

**Issue by jpvajda** [newrelic/newrelic-quickstarts#546]
To help make it easier to identify those PRs with failed PR checks let's add the PR label ` failed check` to these PRs

### Acceptance Criteria

- [ ] All PRs that fail a check should have the label `failed check` added
- [ ] If a PR doesn't have a failed check, the`failed check` label should not be applied. 

### Example  

<img width="403" alt="Screen Shot 2021-11-06 at 10 15 03 AM" src="https://user-images.githubusercontent.com/1395158/140616382-d947b78d-f5b6-48cf-aa7d-4c3e4671e4bc.png">

**Comment by jpvajda** [comment]
I was going to take a crack at this for my innovation time this week.

**Comment by aswanson-nr** [comment]
@jpvajda Not that I don't think this is a great idea, but isn't that already displayed with the green check mark/red X?
<img width="1218" alt="Screen Shot 2022-02-08 at 2 13 39 PM" src="https://user-images.githubusercontent.com/70179303/153084699-8e5c6bbf-8668-46f6-9be1-d9301540074e.png">

If you do go the label route, I would recommend thinking about it from the perspective of a forked PR, since that's where we hit the most restrictions.

**Comment by jpvajda** [comment]
@aswanson-nr it is... but i was thinking it be a more clear indicator on our project board, to see the failed check and perhaps we could measure those counts of failed checks and report on it in a dashboard or something clever.

**Comment by jpvajda** [comment]
closing as this isn't necessary
