### ISSUE TITLE
[Repository] empty config.yml files should fail our repo checks

### ISSUE THREAD

**Issue by jpvajda** [newrelic/newrelic-quickstarts#633]
PR reference  https://github.com/newrelic/newrelic-quickstarts/pull/614 

We had a case where a PR contained empty config files and we allowed the PR checks to pass. We should ensure a config file isn't empty and also contains the correct fields of data on a PR and fail a check so the user knows this isn't allowed.

 if a config file is missing required fields, a PR check fails and the user is notified a config file isn't complete. 

### Acceptance Criteria

- [ ] test if this actually in place already via PR https://github.com/newrelic/newrelic-quickstarts/pull/665/
- [ ] Review the feedback given on a failure case and evaluate if it's helpful. 
- [ ] Review comment from @jbeveland27 and consider our approach
- [ ] Review @jerelmiller's comments for fun. 😉 

### TBD

- [ ] update this [validation workflow ](https://github.com/newrelic/newrelic-quickstarts/blob/main/.github/workflows/validate_packs.yml)to  to check to just run a dry run mutation so we can get back validation errors and then can notify a user their PR is missing required fields.

**Comment by jpvajda** [comment]
I will follow up with DevEx if they are checking for this at the API level.

**Comment by jpvajda** [comment]
From @jbeveland27  

_The PR workflow still needs a bit of lightweight validation on its own to make sure enough of the quickstart is present to construct that mutation input. all the required fields in the mutation must be provided, otherwise the mutation call won't even reach the catalog service. I think the validation workflow needs to be revamped in general. Schema checking doesn't need to occur (i.e. are required fields present), but that data needs to get wrapped up in a mutation call and then the response needs to be inspected. If you don't set the input correctly it doesn't matter what the mutation response is, it'll never get to the service because NerdGraph will just reject it._

**Comment by jerelmiller** [comment]
This seems to me something that should be done repo-side. Keep in mind that we are designing the NerdGraph API in a way that facilitates data from everywhere. Using non-null fields is a way to communicate on our end that a field is required. Empty configuration files should be easy to detect repo-side without needing to run the GraphQL mutation to figure out its invalid.

The only other situation I could see being an issue is having a configuration file that omits non-null fields from the GraphQL mutation. The mutation will error out before it hits our validation because you'd be sending a `null` for a non-null field. There are a couple different ways I could think of to handle this:

1) Parse the error message and pull out the field names.

We get back an error for that in the `errors` key from the response. If you send a mutation that includes `null` values for non-null fields, the error looks something like the following:

```
Argument "quickstartMetadata" has invalid value $quickstart.
In field "summary": Expected type "String!", found null.
In field "icon": Expected type "String!", found null.
In field "displayName": Expected type "String!", found null.
In field "description": Expected type "String!", found null.
In field "authors": Expected type "[Nr1CatalogAuthorInput!]!", found null.
```

We could do some work to look for these kinds of errors and parse out the field names to give a more human-readable error message for the PRs. The pro here is that if we add new fields that are non-null, you shouldn't need to touch this logic since it should be able to parse out new ones. The downside here is that it requires custom string parsing, which may or may not be error prone and you'd have to generate your own error human-readable error messages.

2) Maintain a list of empty "default" values and submit the mutation with those defaults if they are not present in the config file.

In this case, we'd layer in any field that is non-null with an empty value for that field. For a string, this would be an empty string. For a list (like `authors`), this would be an empty array. Doing this gets us past the GraphQL non-null errors, and will instead make it to the service which can give much more readable error messages. If we took this approach, the error messages look something like the following:

```json
"errors": [
    {
      "extensions": {
        "argumentPath": [
          "quickstartMetadata",
          "summary"
        ],
        "errorClass": "VALIDATION_ERROR",
        "nrOnly": {}
      },
      "locations": [
        {
          "column": 3,
          "line": 2
        }
      ],
      "message": "`summary` can't be blank",
      "path": [
        "nr1CatalogSubmitQuickstart"
      ]
    },
    {
      "extensions": {
        "argumentPath": [
          "quickstartMetadata",
          "icon"
        ],
        "errorClass": "VALIDATION_ERROR",
        "nrOnly": {}
      },
      "locations": [
        {
          "column": 3,
          "line": 2
        }
      ],
      "message": "`icon` can't be blank",
      "path": [
        "nr1CatalogSubmitQuickstart"
      ]
    },
    {
      "extensions": {
        "argumentPath": [
          "quickstartMetadata",
          "displayName"
        ],
        "errorClass": "VALIDATION_ERROR",
        "nrOnly": {}
      },
      "locations": [
        {
          "column": 3,
          "line": 2
        }
      ],
      "message": "`displayName` can't be blank",
      "path": [
        "nr1CatalogSubmitQuickstart"
      ]
    },
    {
      "extensions": {
        "argumentPath": [
          "quickstartMetadata",
          "description"
        ],
        "errorClass": "VALIDATION_ERROR",
        "nrOnly": {}
      },
      "locations": [
        {
          "column": 3,
          "line": 2
        }
      ],
      "message": "`description` can't be blank",
      "path": [
        "nr1CatalogSubmitQuickstart"
      ]
    },
    {
      "extensions": {
        "argumentPath": [
          "quickstartMetadata",
          "authors"
        ],
        "errorClass": "VALIDATION_ERROR",
        "nrOnly": {}
      },
      "locations": [
        {
          "column": 3,
          "line": 2
        }
      ],
      "message": "`authors` should include at least 1 author",
      "path": [
        "nr1CatalogSubmitQuickstart"
      ]
    }
```

Pulling out these error messages are trivial, and you would not need to do any custom string parsing here. This is the major pro of this approach.

The downside here is that if we add new non-null fields, you'll need to be aware of them so that we can set an empty default value.

---

Personally I'd choose to go option 2. Its rare we are going to add a new non-null field without first consulting this team. We'd need to make changes to support any new fields from the yaml files, and if we do add them, it should be a 1-line change to add its empty default value.

Don't feel like these are the only options, but definitely something to think about here!

**Comment by jpvajda** [comment]
I spoke a bit more about this with @jerelmiller and his point was in the case of an empty config file, we are missing key sets, and the repo (client) should ensure those keysets are present before making an API request. The service would be checking for values.  However whomever takes this ticket should discuss our approach with Jerel before writing code to can ensure we are on the same page. 📄

**Comment by jpvajda** [comment]
I think we are good on this now, I tested a PR with an empty config and we very clearly throw an error:

https://github.com/newrelic/newrelic-quickstarts/runs/5592566099?check_suite_focus=true

```
Error: quickstarts/empty-config-test/config.yml
	 '#/type' must be object
```

@jerelmiller  @aswanson-nr  would you have concerns if i just marked this as done, since we are now validating with the catalog service, this seems to be resolved.

**Comment by aswanson-nr** [comment]
The initial PR this was created for had literally no content in those files, so that might behave differently than a file with a comment in it. To fully test this out, let's update that test PR to have literally no content in the `config.yml` file.
