### ISSUE TITLE
[Repository] Change all install plans that have `title` to `heading`

### ISSUE THREAD

**Issue by jpvajda** [newrelic/newrelic-quickstarts#824]
### Relate to 

https://github.com/newrelic/newrelic-quickstarts/pull/809

It was confirmed that the [new schema](https://github.com/newrelic/newrelic-quickstarts/blob/main/docs/graphql-schema-docs.md) doesn't use title, but instead heading for the install plans. Though title will still work, we should change all install plans to use heading so it's not confusing to users who may be looking at other install plans for guidance when they create new install plans 

### Acceptance Criteria

- [x] Checkin with DevEx and confirm if this change is OK on their end 
- [ ] IF it's OK, change all install plans that use the title field to use heading 
- [ ] If it's not OK, don't do anything

**Comment by jerelmiller** [comment]
Makes a lot of sense! Let's do this after we enable reading from the database since OILS still expects the `title` field to be there.  Feel free to make the changes, just don't merge any PRs for it yet.

As a general FYI, feel free to make any schema changes on your end as you see fit. The catalog service is completely decoupled from this repo, so any changes you make schema-wise don't affect us at all. The only thing that needs to happen on your end to work with the catalog service is the mapping in the script that sends the data to the catalog service.

Don't feel like you need to get permission from us to make these kinds of changes 🙂

**Comment by jpvajda** [comment]
@jerelmiller I believe we can close this out as won't do now, as heading is going away in the schema? could you confirm when you have a moment.

**Comment by jerelmiller** [comment]
Yep you're right. No sense in tackling this since it will fade away over time.
