### ISSUE TITLE
Publishing quickstart alert policy is not firing

### ISSUE THREAD

**Issue by aswanson-nr** [newrelic/newrelic-quickstarts#930]
## Description
The alert policy for the quickstart submission workflow does not appear to be properly firing when a workflow fails.

## Helpful links
* [troubleshooting dashboard](https://staging.onenr.io/0Z2R58znkwb)
* [alert policy](https://staging.onenr.io/0DvwBAz2bQp)

## Steps to Reproduce
* Review https://github.com/newrelic/newrelic-quickstarts/actions/runs/1995821133/attempts/1
* Notice that there are no alerts in the bots channel for that time range

## Expected Behavior
An alert condition fires off and is visible within the #dev-enablement-bots channel

**Comment by nr-kkenney** [comment]
okayyyyy. some updates. i was initially really confused 🙈  we have this block of code: 

```javascript
const hasFailed = await createValidateUpdateQuickstarts(files);
recordCustomNREvent(hasFailed, isDryRun === 'true');

if (hasFailed) {
  process.exit(1);
}
```

if we look at the erroring workflow, we know we are hitting the process.exit(1) because the step fails. that means `hasFailed` is `true`. heres what really confused me -- if `hasFailed=true`, then the event we are sending in recordCustomNREvent is correct.  so everything is correct, we're just not sending the event. 

if we look in the newrelic UI, we are sending quite a few events -- but all of them are successes, no failures. this is the same for validations vs update mutations.

so to recap:
* code looks correct at every step, but we are not seeing failure events
* in the UI we see no failure events period -- even for validation.

so we see no events for failures, but it looks like it should be sending them. i dont actually know what is mechanically happening under the hood for the newrelic agent, but I had a hunch that because we exit the program nearly immediately after trying to send a custom event, that perhaps the agent wasn't able to send it -- similar to if the program crashes. because this is a github workflow, there isn't an opportunity for the agent to restart and pick up where it left off like it might for a regular apm application.

turns out if i add enough delay to the app as it runs before we exit, we actually send & can see the event in newrelic.
